### ISSUE TITLE
error on adding a new contact email in Spanish admin panel

### ISSUE THREAD

**Issue by nanomo** [oxwall/contactus#6]
This only happens in other language, if i set english i can add new emails, and then translate the new string created: contactus+dept_xxxx

Step to reproduce:
1) set language as spanish from console menu
2) go to admin panel, plugins, contact us settings
3) add a new email, you will get this error(email its added but with no name so the contact from show a empty option in the dropdown box):

```
Type:   Exception
Message:    SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '21746-2' for key 'keyId'
File:   C:\xampp\htdocs\ow_core\database.php
Line:   723
Trace:  #0 C:\xampp\htdocs\ow_core\database.php(723): PDOStatement->execute() #1 C:\xampp\htdocs\ow_core\database.php(476): OW_Database->execute('INSERT INTO `ow...', Array) #2 C:\xampp\htdocs\ow_core\database.php(512): OW_Database->insert('INSERT INTO `ow...', Array) #3 C:\xampp\htdocs\ow_core\base_dao.php(216): OW_Database->insertObject('ow_base_languag...', Object(BOL_LanguageValue)) #4 C:\xampp\htdocs\ow_system_plugins\base\bol\language_service.php(176): OW_BaseDao->save(Object(BOL_LanguageValue)) #5 C:\xampp\htdocs\ow_plugins\contactus\bol\service.php(83): BOL_LanguageService->addValue(2, 'contactus', 'dept_5', 'Error') #6 C:\xampp\htdocs\ow_plugins\contactus\controllers\admin.php(84): CONTACTUS_BOL_Service->addDepartment('error@gmail.com', 'Error') #7 [internal function]: CONTACTUS_CTRL_Admin->dept(Array) #8 C:\xampp\htdocs\ow_core\request_handler.php(276): ReflectionMethod->invokeArgs(Object(CONTACTUS_CTRL_Admin), Array) #9 C:\xampp\htdocs\ow_core\request_handler.php(252): OW_RequestHandler->processControllerAction(Object(ReflectionMethod), Object(CONTACTUS_CTRL_Admin)) #10 C:\xampp\htdocs\ow_core\application.php(364): OW_RequestHandler->dispatch() #11 C:\xampp\htdocs\index.php(76): OW_Application->handleRequest() #12 {main}
```

**Comment by Addenster** [comment]
Hello,

Thanks for report. I've have create a ticket in our internal issue tracker. 
Please, use public forum to report any found bug https://developers.oxwall.com/forum

**Comment by nanomo** [comment]
I will, thanks.
